version: '3'

services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume_focal:/static
    ports:
      - ${APP_PORT}
#    networks:
#      - ncc-333-network

#  nginx:
#    build: nginx
#    restart: always
#    volumes:
#      - static_volume_focal:/static
#    ports:
#      - "80:80"
#    depends_on:
#      - web
#    networks:
#      - ncc-333-network

#networks:
#  ncc-333-network:


volumes:
#  media_volume_focal:
  static_volume_focal: