# Generated by Django 4.2.3 on 2023-07-18 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at datetime')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
